### ISSUE TITLE
Better description

### ISSUE THREAD

**Issue by Olli** [1up-lab/contao-sass-watch#1]
Well I don't know if this tool fits my needs. Maybe its useless maybe not. 
Please add a better description as well as a short description how to use it.

**Comment by bytehead** [comment]
Good point. We will add some more description. There is still one small change hanging. Stay tuned!

**Comment by Olli** [comment]
Thx :)

**Comment by bytehead** [comment]
Added in ded164a379e1a0966e8d96d50200a69b2d22e11e. But this tool is probably still useless to you. We just use this internally during development :)
